plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

repositories {
	mavenLocal()
	maven {
		url = uri('https://repo.maven.apache.org/maven2/')
	}
}

dependencies {
	final def dependency = implementation "org.springframework.boot:spring-boot-starter-web"
	dependency
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation "org.springframework.boot:spring-boot-starter-data-mongodb"
	implementation 'org.projectlombok:lombok:1.18.42'

	annotationProcessor('org.projectlombok:lombok:1.18.42')

	testImplementation "org.springframework.boot:spring-boot-starter-test"
}

group = 'com.lavacro'
version = '3.4.11'
description = 'articles'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

test {
  useJUnitPlatform()
}
